name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv sync

      - name: Run tests
        run: uv run pytest
